### ISSUE TITLE
Add Decision to VASE

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Recipe#1]
any number of decision boxes with one input and two outputs, labelled yes and no.

**Comment by JamesBremner** [comment]
![image](https://github.com/user-attachments/assets/16466ec5-65a6-48ba-8672-73a6b7743b00)

**Comment by JamesBremner** [comment]
TODO:  label outputs YES and NO

**Comment by JamesBremner** [comment]
@lucasgsantos As you can see, I have begun modifying the VASE code as required for recipe.

**Comment by JamesBremner** [comment]
![image](https://github.com/user-attachments/assets/f6ddbe9a-aaef-49c1-9fd6-c142706b616a)

**Comment by JamesBremner** [comment]
@lucasgsantos  I have assigned this issue to you in test.  You will not be able to test it completely until you can build your own clone of the repository.  ( I hope you are working on that - let me know if you hit a snag by opening an issue describing the problem. )  So, for now, just take a look at the screenshot and add any comments to this thread.  If all seems well to you, please close this issue.

**Comment by lucasgsantos** [comment]
- It is possible to delete Start Point, system crashes after Run Recipe
 - Right-click adds a Decision box correctly
 - Selecting the origin and right-clicking the destination adds a arrow (first for No and they for Yes)

**Comment by JamesBremner** [comment]
> Selecting the origin

I don't know what that means.  How do you select the 'origin'?  The origin  of what?

**Comment by JamesBremner** [comment]
Please open a new issue for "selecting the origin" with enough details so that I can reproduce the problem

**Comment by lucasgsantos** [comment]
I just made a comment about how to link 2 objects (origin and destination). It is not an issue

**Comment by JamesBremner** [comment]
OK.  

Note: if you make a comment and it is not an issue, then please make that clear.  Otherwise I will assume that it IS an issue.

**Comment by JamesBremner** [comment]
In general, if something works, then you do not need to bother with a comment.  Just close the issue if it is assigned to you.
