### ISSUE TITLE
Invalid reference to raven-set cxy. error: 'class cxy' has no member named 'zoom'

### ISSUE THREAD

**Issue by lucasgsantos** [JamesBremner/Recipe#4]
C:\e\Projects\projwjb\Recipe>mingw32-make.exe recipe -f .vscode\makefile
g++  -std=c++17 -g -D_mingw_ -Dvase \
-c -o .vscode/obj/cRecipeGUI.o ./src/cRecipeGUI.cpp -I./src -I./src/ext -I./models -I./models/basic -I../windex/include -I../raven-set -I../../code_ext/boost/boost1_78
./src/cRecipeGUI.cpp: In member function 'void cRecipeGUI::drawArrow(wex::shapes&, const cxy&, const cxy&)':
./src/cRecipeGUI.cpp:240:13: error: 'class cxy' has no member named 'zoom'
  240 |     vecLine.zoom(nWidth / sqrt(exit.dist2(entry)));
      |             ^~~~
./src/cRecipeGUI.cpp:246:25: error: no match for 'operator-' (operand types are 'cxy' and 'cxy')
  246 |     arrow[1] = arrow[0] - vecLine;
      |                ~~~~~~~~ ^ ~~~~~~~
      |                       |   |
      |                       cxy cxy
./src/cRecipeGUI.cpp:247:25: error: no match for 'operator+' (operand types are 'cxy' and 'cxy')
  247 |     arrow[2] = arrow[1] + baseLine;
      |                ~~~~~~~~ ^ ~~~~~~~~
      |                       |   |
      |                       cxy cxy
./src/cRecipeGUI.cpp:248:25: error: no match for 'operator-' (operand types are 'cxy' and 'cxy')
  248 |     arrow[3] = arrow[1] - baseLine;
      |                ~~~~~~~~ ^ ~~~~~~~~
      |                       |   |
      |                       cxy cxy
./src/cRecipeGUI.cpp:250:11: error: no matching function for call to 'wex::shapes::line(cxy&, cxy&)'
  250 |     S.line(arrow[4], arrow[0]);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from ./src/cRecipeGUI.cpp:8:
../windex/include/wex.h:619:14: note: candidate: 'void wex::shapes::line(const std::vector<int>&)'
  619 |         void line(const std::vector<int> &v)
      |              ^~~~
../windex/include/wex.h:619:14: note:   candidate expects 1 argument, 2 provided
./src/cRecipeGUI.cpp:251:11: error: no matching function for call to 'wex::shapes::line(cxy&, cxy&)'
  251 |     S.line(arrow[0], arrow[2]);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~
../windex/include/wex.h:619:14: note: candidate: 'void wex::shapes::line(const std::vector<int>&)'
  619 |         void line(const std::vector<int> &v)
      |              ^~~~
../windex/include/wex.h:619:14: note:   candidate expects 1 argument, 2 provided
./src/cRecipeGUI.cpp:252:11: error: no matching function for call to 'wex::shapes::line(cxy&, cxy&)'
  252 |     S.line(arrow[0], arrow[3]);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~
../windex/include/wex.h:619:14: note: candidate: 'void wex::shapes::line(const std::vector<int>&)'
  619 |         void line(const std::vector<int> &v)
      |              ^~~~
../windex/include/wex.h:619:14: note:   candidate expects 1 argument, 2 provided
mingw32-make: *** [.vscode\makefile:44: .vscode/obj/cRecipeGUI.o] Error 1

**Comment by JamesBremner** [comment]
You need to get the latest version from the raven-set repository

**Comment by JamesBremner** [comment]
https://github.com/JamesBremner/raven-set/commit/7c05fc4074eb99f693a1aefe08db3c929f1a85ee

**Comment by lucasgsantos** [comment]
I did
![image](https://github.com/user-attachments/assets/1a892a28-21e4-4be4-b028-d4902d15f5af)

**Comment by JamesBremner** [comment]
You are one commit behind.

**Comment by JamesBremner** [comment]
Note: you will also have to update your windex clone.

**Comment by lucasgsantos** [comment]
No more reference error after updating windex and raven-set
