### ISSUE TITLE
Make not finding boost

### ISSUE THREAD

**Issue by lucasgsantos** [JamesBremner/Recipe#5]
c:\e\Projects\projwjb\Recipe>mingw32-make.exe recipe -f .vscode\makefile
g++  -std=c++17 -g -D_mingw_ -Dvase \
-c -o .vscode/obj/cVase.o ./src/cVase.cpp -I./src -I./src/ext -I./models -I./models/basic -I../windex/include -I../raven-set -I../../code_ext/boost/boost1_78
In file included from ./src/cVase.cpp:8:
./src/tern.h:8:10: fatal error: boost/accumulators/accumulators.hpp: No such file or directory
    8 | #include <boost/accumulators/accumulators.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make: *** [.vscode\makefile:44: .vscode/obj/cVase.o] Error 1

c:\e\Projects\projwjb\Recipe>cd ../../code_ext/boost/boost1_78

c:\e\Projects\code_ext\boost\boost1_78>cd accumulators

c:\e\Projects\code_ext\boost\boost1_78\accumulators>dir accumulators.hpp
 Volume in drive C is Windows-SSD
 Volume Serial Number is 66B5-0B82

 Directory of c:\e\Projects\code_ext\boost\boost1_78\accumulators

10/04/2023  14:47             1.383 accumulators.hpp
               1 File(s)          1.383 bytes
               0 Dir(s)  80.690.798.592 bytes free

c:\e\Projects\code_ext\boost\boost1_78\accumulators>

**Comment by JamesBremner** [comment]
Move

c:\e\Projects\code_ext\boost\

to

c:\e\code_ext\boost\

**Comment by lucasgsantos** [comment]
boost is already 2 folders bellow recipe
I have>
c:\e\Projects\projwjb\Recipe\.vscode\makefile
and
c:\e\Projects\code_ext\boost\boost1_78\accumulators\accumulators.hpp

**Comment by lucasgsantos** [comment]
Folder structure was wrong
It should be
C:\e\Projects\code_ext\boost\boost1_78\boost\accumulators\accumulators.hpp
not
c:\e\Projects\code_ext\boost\boost1_78\accumulators\accumulators.hpp

**Comment by JamesBremner** [comment]
I have removed the dependency on boost.
