### ISSUE TITLE
check for start existence on run

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Recipe#6]
from #1

> It is possible to delete Start Point, system crashes after Run Recipe

**Comment by lucasgsantos** [comment]
System still crashes

![image](https://github.com/user-attachments/assets/8da4217f-9c98-422e-876a-f149a2ff71d8)

**Comment by JamesBremner** [comment]
Yes.

I tried fixing the problem caused when you made a commit to the main branch ( https://github.com/JamesBremner/Recipe/wiki/Collaboration ) but the fix did not work properly. So this and several other of my commits yesterday were broken.

I will do a hard revert and redo the commits.

**Comment by JamesBremner** [comment]
I believe I have fixed the problems without having to do another revert.  Please retest
