### ISSUE TITLE
Re-implement pipe bends

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Recipe#7]
Pipe bends allow connections to avoid unconnected flowers.  The feature got lost on the port to WINDEX.

![image](https://github.com/user-attachments/assets/e53b7a55-9263-4966-8682-3864285bc403)

**Comment by JamesBremner** [comment]
![image](https://github.com/user-attachments/assets/fb14ba6a-e514-4c26-8317-e0ee1724bc8f)

**Comment by lucasgsantos** [comment]
You know what would be great? If the buttons in Message Box had the first Pipebend Question linked to it instead of Yes or No

**Comment by JamesBremner** [comment]
Do not add enhancement requests to the end of closed issues.  Open a new issue.  

What is a "first Pipebend Question"?  Pipebends do not have questions.

**Comment by lucasgsantos** [comment]
[image: image.png]

[image: image.png]



Em qua., 4 de dez. de 2024 às 14:31, James Bremner ***@***.***>
escreveu:

**Comment by JamesBremner** [comment]
Do not add enhancement requests to the end of closed issues.

Your message is unreadable

**Comment by lucasgsantos** [comment]
![unnamed](https://github.com/user-attachments/assets/cff931c0-bf75-4883-a0ee-0fef1d8a5d89)
![unnamed](https://github.com/user-attachments/assets/c77efcfc-be14-4142-a088-aae85b339b44)

**Comment by JamesBremner** [comment]
Do not add to closed questions.  This is the 3rd time I have asked you not to do this.  Why do you keep on doing this?

If you want me to look at something you must open a new issue and assign it to me.
